export const USER_MYDETAILS_REQUEST = 'USER_MYDETAILS_REQUEST'
export const USER_MYDETAILS_SUCCESS = 'USER_MYDETAILS_SUCCESS'
export const USER_MYDETAILS_FAIL = 'USER_MYDETAILS_FAIL'
export const USER_MYDETAILS_RESET = 'USER_MYDETAILS_RESET'

export const USER_UPDATE_MYPROFILE_REQUEST = 'USER_UPDATE_MYPROFILE_REQUEST'
export const USER_UPDATE_MYPROFILE_SUCCESS = 'USER_UPDATE_MYPROFILE_SUCCESS'
export const USER_UPDATE_MYPROFILE_FAIL = 'USER_UPDATE_MYPROFILE_FAIL'
export const USER_UPDATE_MYPROFILE_RESET = 'USER_UPDATE_MYPROFILE_RESET'

export const USER_MYLIST_REQUEST = 'USER_MYLIST_REQUEST'
export const USER_MYLIST_SUCCESS = 'USER_MYLIST_SUCCESS'
export const USER_MYLIST_FAIL = 'USER_MYLIST_FAIL'
export const USER_MYLIST_RESET = 'USER_MYLIST_RESET'
